# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e843ec4de6a85db6e3133c3218a3387727a83d3e0c790346289488136cee38b5f6ef68a722d88b261c41c3e6c61ef91469eb18fefab8b3084b883dd9c7d361

test:
  secret_key_base: 6521cd5eed8a57350beb00f8ca6ac98d73d3f81582f4c6642b5c6b75a6b0ebcf22d8fc88afa3d4619781569e313f1223d426f2b4262134c77404361860ce7a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
